import "./globals.css";
import type { Metadata } from "next";
import { Provider } from "react-redux";
import { store } from "@/services/store";

export const metadata: Metadata = {
  title: "SummarEase",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body>{children}</body>
      </html>
    </Provider>
  );
}
